server:
  port: 8080

spring:
  data:
    redis:
      host: ${SECRET_DB_REDIS_HOST:localhost}
      port: ${SECRET_DB_REDIS_PORT:6379}
  cache:
    type: redis
    redis:
      time-to-live: 300000   # 5 นาที
  kafka:
    bootstrap-servers: ${SECRET_KAFKA_HOST:localhost}:${SECRET_KAFKA_PORT:9092}
    consumer:
      group-id: "my-awesome-app"
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://${SECRET_DB_HOST:localhost}:${SECRET_DB_PORT:5432}/backend
    username: ${SECRET_DB_USERNAME:postgres}
    password: ${SECRET_DB_PASSWORD:syspass}
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB

---
app:
  token:
    secret: ${SECRET_JWT_SECRET:"my-super-secret-key-32-chars-minimum!!"}
    issuer: "BackendService"
